# Generated by Django 5.1.1 on 2024-09-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='service_type',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Consulting', 'Consulting'), ('IT', 'IT'), ('Other', 'Other')], default='Construction', max_length=50),
            preserve_default=False,
        ),
    ]
