# Generated by Django 5.1.1 on 2024-09-13 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_bidversion_tenderversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.employee')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tenders.bid')),
            ],
        ),
    ]
